### ISSUE TITLE
Addition of our ACMMM21 paper

### ISSUE THREAD

**Issue by misogil0116** [LuoweiZhou/YouCook2-Leaderboard#6]
Hi, thank you for such great leaderboard!! 
This is quite useful for my research.

Last year, my paper entitled "State-aware Video Procedural Captioning" has been accepted at ACMMM21.
This paper focuses on generating a procedural text from an instructional video (Paragraph-level) by modeling the state transition of ingredients. Please note that this work uses additional inputs video(clip sequence)+ingredients, not video-only.

Is it ok to submit the paper to the list? If ok, I will create a PR to add this.
```
@inproceedings{taichi2021acmmm,
  title={State-aware Video Procedural Captioning},
  author={Taichi Nishimura and Atsushi Hashimoto and Yoshitaka Ushiku and Hirotaka Kameko and Shinsuke Mori},
  booktitle={ACMMM},
  pages={1766--1774},
  year={2021}
}
```

**Comment by LuoweiZhou** [comment]
Hi @misogil0116, thanks for your interest in our work. Very interesting! Please feel free to submit a PR.

**Comment by misogil0116** [comment]
OK, Thank you!
