### ISSUE TITLE
Youcook2 videos cannot be downloaded

### ISSUE THREAD

**Issue by ttx213** [LuoweiZhou/YouCook2-Leaderboard#8]
I want to download Youcook2 videos, but I am in China now, and the speed is very slow. Could you give me a new download link?

**Comment by weiwuxian1998** [comment]
I also faced this problem, have you obtained the whole raw videos? I would be very appreciated if  you can share them through baiduyun or some similar cloud disks. @ttx213

**Comment by weiwuxian1998** [comment]
you can replace youtube-dl with yt-dlp, the speed will increase greatly

**Comment by ttx213** [comment]
Thank you :)
